dims: [48, 48]
nobj: 2
models: ['bulge+disk']

noise_sigma: 0.01
#noise_sigma: 0.001
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        type: lognormal
        mean: 10.0
        #sigma: 2.0
        sigma: 8.0
        #limits: [0.1, 40.0]

    F:
        type: trackT
        factor: 0.2

fit_model: bdf
