# scale of entire group in arcseconds.  Currently this
# is a gaussian sigma
cluster_scale: 2.0
dims: [48, 48]
nobj: 1
pixel_scale: 0.263

noise_sigma: 0.001
psf_noise_sigma: 0.0001

nband: 3

pdfs:
    g:
        sigma: 0.2

    # hlr of the disk and total flux
    hlr_flux:
        type: cosmos

    disk:
        color: [1.25, 1.0, 0.75]

    bulge:
        color: [0.5, 1.0, 1.5]

        # g_bulge=g_fac*g_disk
        g_fac:
            type: uniform
            range: [0.5, 1.0]


        fracdev:
            type: uniform
            range: [0.0, 1.0]

        # bulge_hlr=hlr_fac*disk_hlr
        hlr_fac: 
            type: uniform
            range: [0.9, 1.1]

        # shift in units of the disk hlr
        bulge_shift: 0.05

    knots:
        color: [1.5, 1.0, 0.5]

        num:
            type: uniform
            range: [1, 100]


        # flux per knot as a fraction of the disk flux
        # so 100 knots would have a total of 1/10 the disk flux
        flux_frac_per_knot: 0.001


fit_model: bdf
