dims: [32, 32]
nobj: 1
models: ["dev"]
noise_sigma: 0.01
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        mean: 4.0
        sigma: 0.01

    F:
        mean: 2.0
        sigma: 0.01

fit_model: "exp"
